//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeFactory1.WebUI.BikeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bike", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Bike : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private BikeFactory1.WebUI.BikeService.ESuspensionType SuspensionTypeField;
        
        private BikeFactory1.WebUI.BikeService.ETireType TireTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public BikeFactory1.WebUI.BikeService.ESuspensionType SuspensionType {
            get {
                return this.SuspensionTypeField;
            }
            set {
                if ((this.SuspensionTypeField.Equals(value) != true)) {
                    this.SuspensionTypeField = value;
                    this.RaisePropertyChanged("SuspensionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public BikeFactory1.WebUI.BikeService.ETireType TireType {
            get {
                return this.TireTypeField;
            }
            set {
                if ((this.TireTypeField.Equals(value) != true)) {
                    this.TireTypeField = value;
                    this.RaisePropertyChanged("TireType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ESuspensionType", Namespace="http://tempuri.org/")]
    public enum ESuspensionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Undefined = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Front = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rear = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dual = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ETireType", Namespace="http://tempuri.org/")]
    public enum ETireType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Undefined = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Regular = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Commuter = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Gravel = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BikeService.BikeServiceSoap")]
    public interface BikeServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        BikeFactory1.WebUI.BikeService.HelloWorldResponse HelloWorld(BikeFactory1.WebUI.BikeService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<BikeFactory1.WebUI.BikeService.HelloWorldResponse> HelloWorldAsync(BikeFactory1.WebUI.BikeService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name Bike from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        BikeFactory1.WebUI.BikeService.InsertResponse Insert(BikeFactory1.WebUI.BikeService.InsertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        System.Threading.Tasks.Task<BikeFactory1.WebUI.BikeService.InsertResponse> InsertAsync(BikeFactory1.WebUI.BikeService.InsertRequest request);
        
        // CODEGEN: Generating message contract since element name Bike from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        BikeFactory1.WebUI.BikeService.UpdateResponse Update(BikeFactory1.WebUI.BikeService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<BikeFactory1.WebUI.BikeService.UpdateResponse> UpdateAsync(BikeFactory1.WebUI.BikeService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        void Delete(int bikeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteAsync(int bikeId);
        
        // CODEGEN: Generating message contract since element name GetListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetList", ReplyAction="*")]
        BikeFactory1.WebUI.BikeService.GetListResponse GetList(BikeFactory1.WebUI.BikeService.GetListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetList", ReplyAction="*")]
        System.Threading.Tasks.Task<BikeFactory1.WebUI.BikeService.GetListResponse> GetListAsync(BikeFactory1.WebUI.BikeService.GetListRequest request);
        
        // CODEGEN: Generating message contract since element name SearchByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchById", ReplyAction="*")]
        BikeFactory1.WebUI.BikeService.SearchByIdResponse SearchById(BikeFactory1.WebUI.BikeService.SearchByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchById", ReplyAction="*")]
        System.Threading.Tasks.Task<BikeFactory1.WebUI.BikeService.SearchByIdResponse> SearchByIdAsync(BikeFactory1.WebUI.BikeService.SearchByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public BikeFactory1.WebUI.BikeService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(BikeFactory1.WebUI.BikeService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public BikeFactory1.WebUI.BikeService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(BikeFactory1.WebUI.BikeService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert", Namespace="http://tempuri.org/", Order=0)]
        public BikeFactory1.WebUI.BikeService.InsertRequestBody Body;
        
        public InsertRequest() {
        }
        
        public InsertRequest(BikeFactory1.WebUI.BikeService.InsertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BikeFactory1.WebUI.BikeService.Bike Bike;
        
        public InsertRequestBody() {
        }
        
        public InsertRequestBody(BikeFactory1.WebUI.BikeService.Bike Bike) {
            this.Bike = Bike;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertResponse", Namespace="http://tempuri.org/", Order=0)]
        public BikeFactory1.WebUI.BikeService.InsertResponseBody Body;
        
        public InsertResponse() {
        }
        
        public InsertResponse(BikeFactory1.WebUI.BikeService.InsertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertResponseBody {
        
        public InsertResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public BikeFactory1.WebUI.BikeService.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(BikeFactory1.WebUI.BikeService.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BikeFactory1.WebUI.BikeService.Bike Bike;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(BikeFactory1.WebUI.BikeService.Bike Bike) {
            this.Bike = Bike;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public BikeFactory1.WebUI.BikeService.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(BikeFactory1.WebUI.BikeService.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateResponseBody {
        
        public UpdateResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetList", Namespace="http://tempuri.org/", Order=0)]
        public BikeFactory1.WebUI.BikeService.GetListRequestBody Body;
        
        public GetListRequest() {
        }
        
        public GetListRequest(BikeFactory1.WebUI.BikeService.GetListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetListRequestBody {
        
        public GetListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListResponse", Namespace="http://tempuri.org/", Order=0)]
        public BikeFactory1.WebUI.BikeService.GetListResponseBody Body;
        
        public GetListResponse() {
        }
        
        public GetListResponse(BikeFactory1.WebUI.BikeService.GetListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BikeFactory1.WebUI.BikeService.Bike[] GetListResult;
        
        public GetListResponseBody() {
        }
        
        public GetListResponseBody(BikeFactory1.WebUI.BikeService.Bike[] GetListResult) {
            this.GetListResult = GetListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchById", Namespace="http://tempuri.org/", Order=0)]
        public BikeFactory1.WebUI.BikeService.SearchByIdRequestBody Body;
        
        public SearchByIdRequest() {
        }
        
        public SearchByIdRequest(BikeFactory1.WebUI.BikeService.SearchByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int bikeId;
        
        public SearchByIdRequestBody() {
        }
        
        public SearchByIdRequestBody(int bikeId) {
            this.bikeId = bikeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public BikeFactory1.WebUI.BikeService.SearchByIdResponseBody Body;
        
        public SearchByIdResponse() {
        }
        
        public SearchByIdResponse(BikeFactory1.WebUI.BikeService.SearchByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BikeFactory1.WebUI.BikeService.Bike SearchByIdResult;
        
        public SearchByIdResponseBody() {
        }
        
        public SearchByIdResponseBody(BikeFactory1.WebUI.BikeService.Bike SearchByIdResult) {
            this.SearchByIdResult = SearchByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BikeServiceSoapChannel : BikeFactory1.WebUI.BikeService.BikeServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BikeServiceSoapClient : System.ServiceModel.ClientBase<BikeFactory1.WebUI.BikeService.BikeServiceSoap>, BikeFactory1.WebUI.BikeService.BikeServiceSoap {
        
        public BikeServiceSoapClient() {
        }
        
        public BikeServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BikeServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BikeServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BikeServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BikeFactory1.WebUI.BikeService.HelloWorldResponse BikeFactory1.WebUI.BikeService.BikeServiceSoap.HelloWorld(BikeFactory1.WebUI.BikeService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            BikeFactory1.WebUI.BikeService.HelloWorldRequest inValue = new BikeFactory1.WebUI.BikeService.HelloWorldRequest();
            inValue.Body = new BikeFactory1.WebUI.BikeService.HelloWorldRequestBody();
            BikeFactory1.WebUI.BikeService.HelloWorldResponse retVal = ((BikeFactory1.WebUI.BikeService.BikeServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BikeFactory1.WebUI.BikeService.HelloWorldResponse> BikeFactory1.WebUI.BikeService.BikeServiceSoap.HelloWorldAsync(BikeFactory1.WebUI.BikeService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<BikeFactory1.WebUI.BikeService.HelloWorldResponse> HelloWorldAsync() {
            BikeFactory1.WebUI.BikeService.HelloWorldRequest inValue = new BikeFactory1.WebUI.BikeService.HelloWorldRequest();
            inValue.Body = new BikeFactory1.WebUI.BikeService.HelloWorldRequestBody();
            return ((BikeFactory1.WebUI.BikeService.BikeServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BikeFactory1.WebUI.BikeService.InsertResponse BikeFactory1.WebUI.BikeService.BikeServiceSoap.Insert(BikeFactory1.WebUI.BikeService.InsertRequest request) {
            return base.Channel.Insert(request);
        }
        
        public void Insert(BikeFactory1.WebUI.BikeService.Bike Bike) {
            BikeFactory1.WebUI.BikeService.InsertRequest inValue = new BikeFactory1.WebUI.BikeService.InsertRequest();
            inValue.Body = new BikeFactory1.WebUI.BikeService.InsertRequestBody();
            inValue.Body.Bike = Bike;
            BikeFactory1.WebUI.BikeService.InsertResponse retVal = ((BikeFactory1.WebUI.BikeService.BikeServiceSoap)(this)).Insert(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BikeFactory1.WebUI.BikeService.InsertResponse> BikeFactory1.WebUI.BikeService.BikeServiceSoap.InsertAsync(BikeFactory1.WebUI.BikeService.InsertRequest request) {
            return base.Channel.InsertAsync(request);
        }
        
        public System.Threading.Tasks.Task<BikeFactory1.WebUI.BikeService.InsertResponse> InsertAsync(BikeFactory1.WebUI.BikeService.Bike Bike) {
            BikeFactory1.WebUI.BikeService.InsertRequest inValue = new BikeFactory1.WebUI.BikeService.InsertRequest();
            inValue.Body = new BikeFactory1.WebUI.BikeService.InsertRequestBody();
            inValue.Body.Bike = Bike;
            return ((BikeFactory1.WebUI.BikeService.BikeServiceSoap)(this)).InsertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BikeFactory1.WebUI.BikeService.UpdateResponse BikeFactory1.WebUI.BikeService.BikeServiceSoap.Update(BikeFactory1.WebUI.BikeService.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public void Update(BikeFactory1.WebUI.BikeService.Bike Bike) {
            BikeFactory1.WebUI.BikeService.UpdateRequest inValue = new BikeFactory1.WebUI.BikeService.UpdateRequest();
            inValue.Body = new BikeFactory1.WebUI.BikeService.UpdateRequestBody();
            inValue.Body.Bike = Bike;
            BikeFactory1.WebUI.BikeService.UpdateResponse retVal = ((BikeFactory1.WebUI.BikeService.BikeServiceSoap)(this)).Update(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BikeFactory1.WebUI.BikeService.UpdateResponse> BikeFactory1.WebUI.BikeService.BikeServiceSoap.UpdateAsync(BikeFactory1.WebUI.BikeService.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<BikeFactory1.WebUI.BikeService.UpdateResponse> UpdateAsync(BikeFactory1.WebUI.BikeService.Bike Bike) {
            BikeFactory1.WebUI.BikeService.UpdateRequest inValue = new BikeFactory1.WebUI.BikeService.UpdateRequest();
            inValue.Body = new BikeFactory1.WebUI.BikeService.UpdateRequestBody();
            inValue.Body.Bike = Bike;
            return ((BikeFactory1.WebUI.BikeService.BikeServiceSoap)(this)).UpdateAsync(inValue);
        }
        
        public void Delete(int bikeId) {
            base.Channel.Delete(bikeId);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int bikeId) {
            return base.Channel.DeleteAsync(bikeId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BikeFactory1.WebUI.BikeService.GetListResponse BikeFactory1.WebUI.BikeService.BikeServiceSoap.GetList(BikeFactory1.WebUI.BikeService.GetListRequest request) {
            return base.Channel.GetList(request);
        }
        
        public BikeFactory1.WebUI.BikeService.Bike[] GetList() {
            BikeFactory1.WebUI.BikeService.GetListRequest inValue = new BikeFactory1.WebUI.BikeService.GetListRequest();
            inValue.Body = new BikeFactory1.WebUI.BikeService.GetListRequestBody();
            BikeFactory1.WebUI.BikeService.GetListResponse retVal = ((BikeFactory1.WebUI.BikeService.BikeServiceSoap)(this)).GetList(inValue);
            return retVal.Body.GetListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BikeFactory1.WebUI.BikeService.GetListResponse> BikeFactory1.WebUI.BikeService.BikeServiceSoap.GetListAsync(BikeFactory1.WebUI.BikeService.GetListRequest request) {
            return base.Channel.GetListAsync(request);
        }
        
        public System.Threading.Tasks.Task<BikeFactory1.WebUI.BikeService.GetListResponse> GetListAsync() {
            BikeFactory1.WebUI.BikeService.GetListRequest inValue = new BikeFactory1.WebUI.BikeService.GetListRequest();
            inValue.Body = new BikeFactory1.WebUI.BikeService.GetListRequestBody();
            return ((BikeFactory1.WebUI.BikeService.BikeServiceSoap)(this)).GetListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BikeFactory1.WebUI.BikeService.SearchByIdResponse BikeFactory1.WebUI.BikeService.BikeServiceSoap.SearchById(BikeFactory1.WebUI.BikeService.SearchByIdRequest request) {
            return base.Channel.SearchById(request);
        }
        
        public BikeFactory1.WebUI.BikeService.Bike SearchById(int bikeId) {
            BikeFactory1.WebUI.BikeService.SearchByIdRequest inValue = new BikeFactory1.WebUI.BikeService.SearchByIdRequest();
            inValue.Body = new BikeFactory1.WebUI.BikeService.SearchByIdRequestBody();
            inValue.Body.bikeId = bikeId;
            BikeFactory1.WebUI.BikeService.SearchByIdResponse retVal = ((BikeFactory1.WebUI.BikeService.BikeServiceSoap)(this)).SearchById(inValue);
            return retVal.Body.SearchByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BikeFactory1.WebUI.BikeService.SearchByIdResponse> BikeFactory1.WebUI.BikeService.BikeServiceSoap.SearchByIdAsync(BikeFactory1.WebUI.BikeService.SearchByIdRequest request) {
            return base.Channel.SearchByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<BikeFactory1.WebUI.BikeService.SearchByIdResponse> SearchByIdAsync(int bikeId) {
            BikeFactory1.WebUI.BikeService.SearchByIdRequest inValue = new BikeFactory1.WebUI.BikeService.SearchByIdRequest();
            inValue.Body = new BikeFactory1.WebUI.BikeService.SearchByIdRequestBody();
            inValue.Body.bikeId = bikeId;
            return ((BikeFactory1.WebUI.BikeService.BikeServiceSoap)(this)).SearchByIdAsync(inValue);
        }
    }
}
